### Q) How to create a project?

- Search in GCP: *"Create Project"*
- Go to *New Project* → Enter *Project Name* → Select *Location → Organization*
- Google provides a default project name, which you can change later.
- *We can change the Project Name anytime* after creating it.
- *You cannot create an Organization using a free personal Gmail account.*
- You can create multiple projects with the *same project name, but Google will always assign a **unique Project ID*.
- In GCP, *billing is associated at the project level*.
- When you *shut down (delete)* a Google Cloud project, *everything inside it is removed*.

---

### Project ID vs Project Number

#### Project ID
- Human-readable
- Globally unique
- You choose it when creating the project
- Used in APIs, SDKs, CLI commands, bucket names, service accounts

#### Project Number
- Automatically generated by Google
- Cannot be changed
- Always unique inside GCP
- Purely numeric (used internally for resource identification)
